mkdir -p html/images
cd html/images
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ad.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ae.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/af.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ag.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ai.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/al.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/am.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/an.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ao.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/aq.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ar.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/as.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/at.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/au.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/aw.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/az.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ba.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bb.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bd.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/be.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bf.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bg.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bh.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bi.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bj.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bn.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bo.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/br.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bs.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bt.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bv.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bw.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/by.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/bz.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ca.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cc.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cf.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cg.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ch.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ci.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ck.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cl.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cn.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/co.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cs.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cu.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cv.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cx.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cy.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/cz.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/de.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/dj.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/dk.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/dm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/do.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/dz.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ec.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ee.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/eg.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/eh.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/er.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/es.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/et.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/fi.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/fj.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/fk.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/fm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/fo.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/fr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/fx.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ga.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gb.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gd.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ge.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gf.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gh.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gi.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gl.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gn.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gp.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gq.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gs.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gt.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gu.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gw.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gy.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/hk.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/hm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/hn.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/hr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ht.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/hu.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/id.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ie.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/il.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/in.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/io.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/iq.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ir.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/is.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/it.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/jm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/jo.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/jp.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ke.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/kg.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/kh.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ki.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/km.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/kn.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/kp.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/kr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/kw.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ky.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/kz.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/la.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/lb.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/lc.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/li.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/lk.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/lr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ls.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/lt.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/lu.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/lv.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ly.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ma.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mc.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/md.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mg.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mh.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mk.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ml.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mn.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mo.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mp.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mq.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ms.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mt.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mu.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mv.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mw.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mx.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/my.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mz.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/na.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/nc.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ne.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/nf.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ng.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ni.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/nl.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/no.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/np.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/nr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/nt.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/nu.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/nz.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/om.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/pa.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/pe.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/pf.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/pg.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ph.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/pk.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/pl.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/pm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/pn.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/pr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/pt.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/pw.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/py.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/qa.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/re.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ro.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ru.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/rw.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sa.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sb.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sc.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sd.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/se.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sg.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sh.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/si.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sj.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sk.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sl.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sn.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/so.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/st.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/su.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sv.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sy.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/sz.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tc.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/td.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tf.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tg.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/th.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tj.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tk.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tn.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/to.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tp.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tt.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tv.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tw.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/tz.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ua.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ug.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/uk.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/um.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/us.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/uy.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/uz.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/va.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/vc.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ve.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/vg.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/vi.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/vn.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/vu.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/wf.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ws.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/ye.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/yt.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/yu.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/za.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/zm.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/zr.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/zw.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/com.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/edu.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/gov.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/int.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/mil.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/net.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/org.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/arpa.gif
wget -N --header "user-agent:1" http://bgp.he.net/images/flags/nato.gif
